### ISSUE TITLE
1D chi^2 calculated incorrectly

### ISSUE THREAD

**Issue by admorris** [abmorris/RapidFit#11]
`ComponentPlotter` just evaluates the PDF in the middle of the bin and scales it by some factor to get the number of expected events. This is only valid for functions that are straight lines. The correct thing would be to integrate between the bin boundaries.

**Comment by admorris** [comment]
Probably fixed with [`a754f11`](https://github.com/abmorris/RapidFit/commit/a754f1174629d4305b09c234698f6c4985c3f2fa)

**Comment by admorris** [comment]
Assume this is fixed for now. Also the pulls.

**Comment by kgizdov** [comment]
Btw, nowhere in this entire class (`ComponentPlotter`) is full_boundary checked if `NULL`. It is, however, initialized as `NULL`. Should it not be `nullptr`? Or better yet just `{}`. Why is `new PhaseSpaceBoundary` assumed to never fail? Baring in mind that this is a private member, wouldn't it better be a regular object rather than a pointer? Getters and Setters could be made to handle pointer-like return/input cases where pointer is needed.

**Comment by admorris** [comment]
Strange place to put this comment, but yeah those are all valid points. I don't have the time to completely re-write this class, although it seems like I'm re-writing big chunks of it anyway.
